### ISSUE TITLE
Change "license" to public domain?

### ISSUE THREAD

**Issue by aalex** [qaap/qml-kickstart#1]
Hi,
This is great. I release examples in the public domain, so that developers can simply choose the license they want and won't need to put the authors of the example as authors of their software. Is this something you might consider?
For example: https://github.com/aalex/txosc/blob/master/examples/async_multicast_receiver.py#L7
Thank you.

**Comment by pkoretic** [comment]
Hi.

Idea was that it is more like an [HTML5 Boilterplate](https://html5boilerplate.com) which is also under MIT License.

We will definitely investigate and take a look. Thanks for your suggestion!

**Comment by pkoretic** [comment]
Sorry for the late response. 

We will keep it under MIT for now as we plan to extend it into a small boilerplate framework for cross platform development. Although I don't mind to release it under public domain as I've done this before. If you would be so kind to make a pull request with these changes I would be happy to accept it. 

Thanks.
